//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryBaseEntitiess : DbContext
    {
        public LibraryBaseEntitiess()
            : base("name=LibraryBaseEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category_materials> category_materials { get; set; }
        public virtual DbSet<list__of_posts> list__of_posts { get; set; }
        public virtual DbSet<list_employees> list_employees { get; set; }
        public virtual DbSet<materials> materials { get; set; }
        public virtual DbSet<order_composition> order_composition { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
