//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_composition
    {
        public int order_id { get; set; }
        public int nomer_zakaza { get; set; }
        public int nomer_sotrudnika { get; set; }
        public int kod_uslugi { get; set; }
        public decimal tarif { get; set; }
        public long kolichestvo_uslug { get; set; }
        public long material_kod { get; set; }
        public long kolichestvo_material { get; set; }
    
        public virtual list_employees list_employees { get; set; }
        public virtual materials materials { get; set; }
        public virtual orders orders { get; set; }
        public virtual services services { get; set; }
    }
}
