//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.order_composition = new HashSet<order_composition>();
        }
    
        public int nomer_zakaza { get; set; }
        public string imya { get; set; }
        public string familiya { get; set; }
        public string adress { get; set; }
        public Nullable<long> telephone { get; set; }
        public System.DateTime data_zakaza { get; set; }
        public System.DateTime data_vipolneniya { get; set; }
        public string otchestvo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_composition> order_composition { get; set; }
    }
}
